### ISSUE TITLE
Only part of post is rendered

### ISSUE THREAD

**Issue by adelura** [hostilefork/hostilefork.com#6]
Hey, I started to read your [post](https://www.readability.com/articles/jffc2v0t) and it seems it doesn't work properly. Post ends with "As we all know, to use a JavaScript file in a web page you use a".

**Comment by hostilefork** [comment]
Thank you very much for the report!!

Such are the dangers of developing [your own content format](https://github.com/hostilefork/hostilefork.com/blob/master/entries/posts/sharing-code-client-server-nodejs), your own site generator in a [relatively unknown language](http://blog.hostilefork.com/why-rebol-red-parse-cool/), and using development builds of that language that you yourself are hacking on the C for to build your website. 

[Back up](http://blog.hostilefork.com/sharing-code-client-server-nodejs/)...until I break something again.  :-)
